image: node:latest

services:
    - mysql:latest
variables:
    MYSQL_DATABASE: "fridge"
    MYSQL_ROOT_PASSWORD: "fish"

stages:
    - test
    - build
    - deploy

test_backend:
    stage: test
    script:
        - cd backend
        - npm test
        - flow check server.js database/*.js

test_frontend:
    stage: test
    script:
        - cd frontend
        - npm test
        - flow check src

build:
    stage: build
    script:
      - echo '"building"...'

deploy:
    stage: deploy
    script:
        - echo '"deploying"...'
    only:
        - master
