image: node:latest

stages:
    - test
    - coverage
    - build
    - deploy

test_backend:
    stage: test
    services:
        - mysql:5
    variables:
        MYSQL_DATABASE: "fridge"
        MYSQL_ROOT_PASSWORD: "fish"
    script:
        - cd backend
        - npm install -g flow-bin
        - npm install
        - npm test
        - flow check
    artifacts:
        paths:
            - backend/coverage/

test_frontend:
    stage: test
    script:
        - cd frontend
        - npm install -g flow-bin
        - npm install
        - npm test
        - flow check src
    artifacts:
        paths:
            - frontend/coverage/

pages:
    stage: coverage
    script:
        - mkdir -p .public/{front,back}end
        - cp -r backend/coverage/* .public/backend
        - cp -r frontend/coverage/* .public/frontend
        - mv .public public
    artifacts:
        paths:
            - public/
    only:
        - master

build:
    stage: build
    script:
      - echo '"building"...'

deploy:
    stage: deploy
    script:
        - echo '"deploying"...'
    only:
        - master
