image: node:latest

#services:
#    - mysql:latest

stages:
    - build
    - test
    - deploy

build:
    stage: build
    script:
    - npm install
    artifacts:
        paths:
        - node_modules
    only:
    - master

test:
    stage: test
    script:
    - node test.js
    - ls node_modules

deploy:
    stage: deploy
    script:
    - echo '"deploying"...'

