image: node:latest

services:
    - mysql:latest
variables:
    MYSQL_DATABASE: "fridge"
    MYSQL_ROOT_PASSWORD: "fish"

stages:
    - build
    - test
    - deploy

build:
    stage: build
    script:
      - npm install
    artifacts:
        paths:
        - node_modules

test:
    stage: test
    script:
        - npm test

deploy:
    stage: deploy
    script:
        - echo '"deploying"...'
    only:
        - master
