image: node:latest

stages:
    - test
    - build
    - deploy

test_backend:
    stage: test
    services:
        - mysql:5
    variables:
        MYSQL_DATABASE: "fridge"
        MYSQL_ROOT_PASSWORD: "fish"
    script:
        - cd backend
        - npm install -g flow-bin
        - npm install
        - npm test
        - flow check

test_frontend:
    stage: test
    script:
        - cd frontend
        - npm install -g flow-bin
        - npm install
        - npm test
        - flow check src

build:
    stage: build
    script:
      - echo '"building"...'

deploy:
    stage: deploy
    script:
        - echo '"deploying"...'
    only:
        - master
