image: node:latest

#services:
#    - mysql:latest

build:
    stage: build
    script:
    - npm install
    artifacts:
        paths:
        - node_modules
    only:
    - master

test:
    stage: test
    script:
    - node test.js
    - echo hello
