name: Test the Fridge

on: [push]

jobs:
  test_backend:
    runs-on: ubuntu-latest
    # for the sake of MySQL sanity
    container: ubuntu

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306
        env:
          MYSQL_DATABASE: 'fridge'
          MYSQL_ROOT_PASSWORD: 'fish'
        # Health check that ensures the service is up and running before tests start to run
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - name: Install dependencies
        run: |
          cd backend
          npm install
          npm install -g flow-bin flow-coverage-report
          apt-get update && apt-get upgrade -y
          apt-get install -y libatomic1
      - name: Perform tests
        run: |
          cd backend
          npm test
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
      - name: Perform typechecking
        run: cd backend && flow check .
      - name: Analyze flow coverage
        run: cd backend && npm run flow-coverage

  test_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - name: Install dependencies
        run: |
          cd frontend
          npm install
          npm install -g flow-bin flow-coverage-report
          apt-get install -y libatomic
      - name: Perform tests
        run: cd frontend && npm install && npm test
      - name: Perform typechecking
        run: cd frontend && flow check src
      - name: Analyze flow coverage
        run: cd frontend && npm run flow-coverage
