name: Test the Fridge

on: [push]

jobs:
  test_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - name: Shutdown default MySQL service
          run: sudo service mysql stop
      # Set up MySQL database
      - uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '5.7'
          mysql database: 'fridge'
          mysql root password: 'fish'
      - name: Install dependencies
        run: cd backend && npm install && sudo npm install -g flow-bin flow-coverage-report
      - name: Perform tests
        run: cd backend && npm test
      - name: Perform typechecking
        run: cd backend && flow check src
      - name: Analyze flow coverage
        run: cd backend && npm run flow-coverage

  test_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - name: Install dependencies
        run: cd frontend && npm install && sudo npm install -g flow-bin flow-coverage-report
      - name: Perform tests
        run: cd frontend && npm test
      - name: Perform typechecking
        run: cd frontend && flow check src
      - name: Analyze flow coverage
        run: cd frontend && npm run flow-coverage
